## Exercises

Set up a new local and remote called ds-libraries-exercises for this module.

Let's review the steps to get setup.

Create a new repository named ds-libraries-exercises on GitHub.com

Copy the SSH link for this repository

In the terminal, navigate to ~/codeup-data-science

Clone your remote repository to your local using: git clone + the link you copied

Create a .gitignore

Create a README.md file that outlines the purpose of this repository

Add, commit, and push these two files.

Go to GitHub.com and very that the .gitignore and README.md are there

In your new repo, create a file named numpy_exercises.py or numpy_exercises.ipynb for this exercise.

Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])




### Awesome Bonus 
For much more practice with numpy, go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop.

To clone a repository:

Copy the SSH address of the repository

In your terminal, run cd ~/codeup-data-science (goes to your codeup-data-science folder)

Run git clone git@github.com:rougier/numpy-100.git (clones down Rougeir's files)

Run cd numpy-100 (move into the numpy folder)

Run git remote remove origin (so you won't accidentally try to push your work to Rougier's repo)

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

Go to https://github.com/new to make a new repo. Name it numpy-100.

DO NOT check any check boxes. We need a blank, empty repo.

Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

Now do work, add it, commit it, and push it!

In [1]:
import numpy as np #industry standard

## Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
a=np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

## Q1) How many negative numbers are there?


In [3]:
# 1st method:-
a[a<0]

array([-2, -1, -6, -7])

In [4]:
np.sum(a<0)

4

In [5]:
# 2nd method (mask boolean method):-
mask=a<0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [6]:
new_array=a[mask]
new_array

array([-2, -1, -6, -7])

In [7]:
len(new_array)

4

In [8]:
#3rd method:

(a<0).sum()

4

## Q2) How many positive numbers are there?


In [9]:
#1st method:-
a[a>0]

array([ 4, 10, 12, 23,  3])

In [10]:
len(a[a>0])

5

In [11]:
#2nd method:-
np.sum(a>0)

5

In [12]:
#3rd method:-
(a>0).sum()

5

## Q3 How many even positive numbers are there?

In [13]:
# 1st method:-
np.sum((a>0) & (a%2==0))

3

In [14]:
# 2nd method:-
len(a[a>0])

5

In [15]:
#3rd method:-
(a>0).sum()

5

## Q4) If you were to add 3 to each data point, how many positive numbers would there be?

In [16]:
#1st method:-
# add 3 to given array
add=a+3
add

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [17]:
np.sum(add>0)

10

In [18]:
#2nd method:-
((a+3)>0).sum()

10

In [19]:
#3rd method:-
(a+3)[(a+3)>0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [20]:
len((a+3)[(a+3)>0])

10

## Q5) If you squared each number, what would the new mean and standard deviation be?


In [21]:
squared=a**2
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [22]:
# by using function
np.mean(squared)

74.0

In [23]:
# by using method
squared.mean()

74.0

In [24]:
# using function
np.std(squared)

144.0243035046516

In [25]:
# by using method
squared.std()

144.0243035046516

## Q6) 

A common statistical operation on a dataset is centering. 

This means to adjust the data such that the mean of the data is 0. 

This is done by subtracting the mean from each data point. Center the data set. 

See this link for more on centering.

In [26]:
a.mean()

3.0

In [27]:
mean_a=a.mean()
mean_a

3.0

In [28]:
new_a=a-3
new_a

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [29]:
new_mean=new_a.mean()
new_mean

0.0

## Q7) Calculate the z-score for each data point. Recall that the z-score is given by:

                    Z=(x−μ)/σ
                    
                    #latex in markdown
                    


In [30]:
mean_a=a.mean()
mean_a

3.0

In [31]:
std_a=a.std()
std_a

8.06225774829855

In [32]:
z=(a-mean_a)/std_a
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## Q8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


More Numpy Pracitce has link (click there)

## Q8) Setup 1: Life w/o numpy to life with numpy

Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [33]:

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:

sum_of_a=sum(a)
sum_of_a

55

In [35]:
min_of_a=min(a)
min_of_a

1

In [36]:
max_of_a=max(a)
max_of_a

10

In [37]:
mean_of_a=sum_of_a/len(a)
mean_of_a

5.5

In [38]:
product_of_a=1
for x in a:
    product_of_a *=x
print("product of all the numbers in the list a:--",product_of_a)
    

product of all the numbers in the list a:-- 3628800


In [39]:
squares_of_a=[x**2 for x in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [40]:
# another way:

squares_of_a=[]
for x in a:
    squares_of_a.append(x**2)
print("squares_of_a=",squares_of_a)

squares_of_a= [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [41]:
odd_in_a=[]
for x in a:
    if x%2==1:
        odd_in_a.append(x)
odd_in_a

[1, 3, 5, 7, 9]

In [42]:
even_in_a=[]
for x in a:
    if x%2==0:
        even_in_a.append(x)
even_in_a

[2, 4, 6, 8, 10]

## Q8-setup2

- What about life in two dimensions? 

- A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

            b = [[3, 4, 5],[6, 7, 8]]
            

Exercise 1 - refactor the following to use numpy. 
Use sum_of_b as the variable. 
Hint, you'll first need to make sure that the "b" variable is a numpy array

sum_of_b = 0 
for row in b: 
    sum_of_b += sum(row)


Exercise 2 - refactor the following to use numpy.
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])


Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1 for row in b: for number in row: product_of_b *= number


Exercise 6 - refactor the following to use numpy to find the list of squares
squares_of_b = [] for row in b: for number in row: squares_of_b.append(number**2)


Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = [] for row in b: for number in row: if(number % 2 != 0): odds_in_b.append(number)


Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = [] for row in b: for number in row: if(number % 2 == 0): evens_in_b.append(number)


Exercise 9 - print out the shape of the array b.


Exercise 10 - transpose the array b.


Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)



In [43]:
b = [[3, 4, 5],[6, 7, 8]]

In [44]:
import numpy as np

In [45]:
# converting b into Numpy Array:-
b=np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

## Q8-setup2-Ex1

Exercise 1 - refactor the following to use numpy. 

Use sum_of_b as the variable. 

Hint, you'll first need to make sure that the "b" variable is a numpy array

sum_of_b = 0 

for row in b: 

    sum_of_b += sum(row)
    
    


In [46]:
# refactor =rewrite

# 1st way (by using numpy function)
sum_of_b=np.sum(b)
sum_of_b

33

In [47]:
# another way( by using numpy object method):-

sum_of_b=b.sum()
sum_of_b

33

## Q8-setup2-Ex2
refactor the following to use numpy.

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])


In [48]:
# by using method:
min_of_b=b.min()
min_of_b

3

In [49]:
# by numpy function

min_of_b=np.min(b)
min_of_b

3

## Q8-setup2-Ex3
refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


In [50]:
max_of_b=np.max(b)
max_of_b

8

## Q8-setup2-Ex4
refactor the following using numpy to find the mean of b

mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


In [51]:
mean_of_b=np.mean(b)
mean_of_b

5.5

## Q8-setup2-Ex5
refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1 

for row in b:

    for number in row:

        product_of_b *= number


In [52]:
product_of_b=np.prod(b)
product_of_b

20160

## Q8-setup2-Ex6
refactor the following to use numpy to find the list of squares

squares_of_b = [] for row in b: for number in row: squares_of_b.append(number**2)


In [53]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

## Q8-setup2-Ex7
refactor using numpy to determine the odds_in_b

odds_in_b =[]

for row in b: 

    for number in row: 

        if(number % 2 != 0): 
            
            odds_in_b.append(number)


In [54]:
b[b%2==1]

array([3, 5, 7])

## Q8-setup2-Ex8
refactor the following to use numpy to filter only the even numbers

evens_in_b = [] 

for row in b: 

    for number in row: 

        if(number % 2 == 0): 

            evens_in_b.append(number)


In [55]:
b[b%2==0]

array([4, 6, 8])

## Q8-setup2-Ex9

print out the shape of the array b.

In [56]:
b

array([[3, 4, 5],
       [6, 7, 8]])

## Q8-setup2-Ex10

transpose the array b.

In [57]:
np.transpose(b) # numpy function

array([[3, 6],
       [4, 7],
       [5, 8]])

## Q8-setup2-Ex11

reshape the array b to be a single list of 6 numbers. (1 x 6)

In [58]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [59]:
np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

## Q8-setup2-Ex12
reshape the array b to be a list of 6 lists, each containing only 1 

number (6 x 1)


In [60]:
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Q8-setup3

Setup 3

c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.



In [61]:
c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [62]:
c=np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Q8-setup3-Ex1
Find the min, max, sum, and product of c.

In [63]:
c.min(), c.max(), c.sum(), c.prod()


(1, 9, 45, 362880)

## Q8-setup3-Ex2
Determine the standard deviation of c.

In [64]:
c.std()

2.581988897471611

## Q8-setup3-Ex3
Determine the variance of c.

In [65]:
c.var()

6.666666666666667

## Q8-setup3-Ex4
Print out the shape of the array c

In [66]:
c.shape # attribute of object

(3, 3)

## Q8-setup3-Ex5
Transpose c and print out transposed result.

In [67]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Q8-setup3-Ex6
Get the dot product of the array c with c.

In [69]:
c*c # not a dot product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [70]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## Q8-setup3-Ex7
Write the code necessary to sum up the result of c times c transposed. 

Answer should be 261

In [71]:
c.T*c

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [72]:
(c.T*c).sum()

261

## Q8-setup3-Ex8
Write the code necessary to determine the product of c times c transposed. 

Answer should be 131681894400.

In [73]:
(c.T*c).prod()

131681894400

## Q8-Setup 4
d = [ [90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180] ]

Exercise 1 - Find the sine of all the numbers in d

Exercise 2 - Find the cosine of all the numbers in d

Exercise 3 - Find the tangent of all the numbers in d

Exercise 4 - Find all the negative numbers in d

Exercise 5 - Find all the positive numbers in d

Exercise 6 - Return an array of only the unique numbers in d.

Exercise 7 - Determine how many unique numbers there are in d.

Exercise 8 - Print out the shape of d.

Exercise 9 - Transpose and then print out the shape of d.

Exercise 10 - Reshape d into an array of 9 x 2

In [74]:
d = [ [90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180] ]
d

[[90, 30, 45, 0, 120, 180],
 [45, -90, -30, 270, 90, 0],
 [60, 45, -45, 90, -45, 180]]

In [75]:
d=np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [76]:
# Example 1
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [77]:
# Example 2
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [78]:
# Example 3
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [79]:
# Example 4
d


array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [80]:
d[d<0]

array([-90, -30, -45, -45])

In [81]:
# Example 5
mask=d>0
mask

array([[ True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True, False],
       [ True,  True, False,  True, False,  True]])

In [82]:
d[mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [83]:
# Example 6
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [84]:
#Example 7
np.count_nonzero(np.unique(d))   #dont use this (it does not include 0)

10

In [85]:
len(np.unique(d))

11

In [86]:
# Example 8

d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [87]:
d.shape

(3, 6)

In [88]:
# Example 9
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [89]:
d.T.shape

(6, 3)

In [90]:
# Example 10
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])